### ISSUE TITLE
Unable to Install SpiecEasi

### ISSUE THREAD

**Issue by kbazany** [zdk123/SpiecEasi#225]
Hello, 

I am having trouble installing SpiecEasi. I have MASS, pulsar, and huge. Are there other dependencies I'm missing? I am working on a MacOS 12.6. The errors I am getting are "directory not found" and "compilation failed"

Here is the full error message: 

install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@HEAD
✔  checking for file ‘/private/var/folders/fw/zd4dlkh57zsc9c9tzdzz_8cw0000gn/T/RtmpfIXk3W/remotes5f647ac0aabe/zdk123-SpiecEasi-c463727/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.2.tar.gz’
   
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c svthresh.cpp -o svthresh.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/fw/zd4dlkh57zsc9c9tzdzz_8cw0000gn/T//RtmpfIXk3W/file5f647f09dee7/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status

Thank you!

**Comment by kbazany** [comment]
No sorry! I haven't gotten an answer yet! I'll let you know if I figure it out!
________________________________

**Comment by LauraBMar** [comment]
Hi, 

I am also having the same problem.

I want to install NetCoMi in my MacOS, and I followed the advice to install first mixed CCA, and then SpiecEasi. 

When I try to install SpiecEasi, it firsts ask me to update these packages; 
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                           
2: CRAN packages only                            
3: None                                          
4: igraph       (1.5.0.1    -> 1.5.1     ) [CRAN]
5: RcppArmad... (0.12.4.1.0 -> 0.12.6.1.0) [CRAN]

And then results in this error; 

ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/v2/jm6fgmfn6v9dtmd95l92nl600000gn/T//RtmpDMxP6Y/file56a34c2cf80b/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status


I don´t know what should I do. Is there a known solution by now?


Thanks in advance for your help, 

Laura
